name: Docker Image Fetch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -f twitter-fetch-service/Dockerfile . -t twitter-fetch-service:$(date +%s)
